### ISSUE TITLE
Add tidynamics to conda recipe

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/mdanalysistests-feedstock#17]
Issue:

Tidynamics >=1.0.0 needs to be added to feedstock for the new msd analysis module. Related PR https://github.com/MDAnalysis/mdanalysis/pull/2619

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by richardjgowers** [comment]
This only needs to get merged once the release with MSD is out, but I’ll
leave it up as a reminder.

**Comment by orbeckst** [comment]
that was done ... some time
