### ISSUE TITLE
check new noarch packages

### ISSUE THREAD

**Issue by orbeckst** [conda-forge/mdanalysistests-feedstock#36]
### Comment:

With PR #33 a noarch package is uploaded to conda-forge https://anaconda.org/conda-forge/mdanalysistests/files.

However, I looked at the azp output for [run #20220705.1](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=531552&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d) and saw a few things that seem questionable:

**Why is a py2.py3 wheel being built?**
```
Created wheel for MDAnalysisTests: filename=MDAnalysisTests-2.2.0-py2.py3-none-any.whl size=52786848 sha256=80227459b4f0bd9ec20eee61cfc6f01797a8d0298b9941f2889f8c16b615e9c3
  Stored in directory: /tmp/pip-ephem-wheel-cache-_uc1fhgj/wheels/d2/c3/c3/fa7e2ea883f0e271a24d053f9a47d02ef2b51fface1ae2ebb4
```
([I don't think that the wheel is uploaded](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=531552&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1926) but it looks suspicious to me because we do NOT support Py 2.) 

**Numpy version is not pinned in the same way as MDAnalysis:**

[No numpy version specified in conda_build_config.yaml.](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=531552&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1952)

**`conda verify` fails (because it is not installed??)**

[WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=531552&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1687)

**Comment by orbeckst** [comment]
@IAlibay @tylerjereddy do you know if any of the above should raise alarm bells?

**Comment by IAlibay** [comment]
I'll double check in the morning but I _think_ that's all fine. The fact that we get universal wheels might just be a reflection of how conda forge does noarch.

**Comment by IAlibay** [comment]
We're building universal wheels because we have universal set in our setup.cfg 🤦🏾‍♂️

**Comment by orbeckst** [comment]
Oops, then that was one of tyhe things we purged from the mdanalysis package build but apparently forgot for the testsuite.

**Comment by IAlibay** [comment]
I'll test the build now, I think it won't matter for our purposes though since the dependency chain will limit it to what MDA 2.2.0 supports

**Comment by IAlibay** [comment]
All tests pass, so I'm going to close this issue with the following comments.

> Why is a py2.py3 wheel being built?

I've removed the wheel sections from both mdanalysis and mdanalysistests, so this won't be an issue anymore. It doesn't really affect us here so it's fine to carry on with this build.

> Numpy version is not pinned in the same way as MDAnalysis

MDAnalysisTests doesn't have any ABI requirements so we don't need to pin to a given numpy version anyways. If we want to we can / should define a minimum numpy version under the package's setup.py. However, given that it requires MDAnalysis, the numpy runtime version ends up being the same range as what is allowed by the MDAnalysis package.

> conda verify fails (because it is not installed??)

We can safely ignore this, see: https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-conda-verify
